$source = 'minutes.tex'
$output = $source.sub('.tex', '.pdf')
$dependencies = [] + Dir.glob('**/*.tex') + Dir.glob('./*.sty') + Dir.glob('./*.cls')
$byproducts = %w{*.out *.log *.aux *.toc}
$published_output = "../#{File.basename(Dir.pwd)}.pdf"

$lc = 'xelatex'
$lf = '-file-line-error -halt-on-error'

file $output => [$source, *$dependencies] do |t|
  2.times { sh "#{$lc} #{$lf} #{t.prerequisites[0]}" }
end

task :default => :build

task :build => $output

task :show => $output do
  os = case `uname`.strip when 'Darwin' then :mac else :linux end
  case os
  when :mac
    sh "open #{$output}"
  else
    sh "xpdf #{$output} &"
  end
end

task :publish => $output do
  sh "mv #{$output} #{$published_output}"
end

task :clean do
  $byproducts.each { |file| sh "rm -f #{file}" }
end
