package algs;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;


@RunWith(Suite.class)
@Suite.SuiteClasses({
    algs.example.tests.chapter5.wordlist.WordListHashTableTest.class,
    algs.example.tests.chapter7.TestVariableJumping.class,
    algs.example.tests.chapter7.fifteenSolitaireJumping.AllSolutions.class,
    algs.example.tests.chapter7.fifteenSolitaireJumping.TestJumping.class,
    algs.example.tests.chapter7.fifteenSolitaireJumping.TestRevisedJumping.class,
    algs.example.tests.model.pseudocodeExample.PrepareFigures.class,
    algs.example.tests.model.pseudocodeExample.PrepareGameTreeFigures.class,
    algs.model.tests.array.QuickSortTest.class,
    algs.model.tests.array.ValidateSelectionTest.class,
    algs.model.tests.chapter4.SortTest.class,
    algs.model.tests.chapter7.RecursionOptionsTest.class,
    algs.model.tests.convexhull.DoubleTest.class,
    algs.model.tests.convexhull.FloatingPointTest.class,
    algs.model.tests.convexhull.HullComparisonsTest.class,
    algs.model.tests.convexhull.HullTest.class,
    algs.model.tests.convexhull.InterestingCaseTest.class,
    algs.model.tests.convexhull.LinkedListComparisonTest.class,
    algs.model.tests.convexhull.PartialTest.class,
    algs.model.tests.convexhull.RingsTest.class,
    algs.model.tests.convexhull.SlowHullTest.class,
    algs.model.tests.data.CatchAllTest.class,
    algs.model.tests.data.GeneratorsTest.class,
    algs.model.tests.data.MoreGeneratorsTest.class,
    algs.model.tests.eightpuzzle.EvaluationTest.class,
    algs.model.tests.eightpuzzle.KeyTest.class,
    algs.model.tests.eightpuzzle.NodeTest.class,
    algs.model.tests.fifteenpuzzle.FifteenPuzzleTest.class,
    algs.model.tests.fifteenpuzzle.SlideMoveTest.class,
    algs.model.tests.fp.ExampleFloatingPointTest.class,
    algs.model.tests.gametree.AlphaBetaOnSameBoardAsNegMaxTest.class,
    algs.model.tests.gametree.AlphaBetaTest.class,
    algs.model.tests.gametree.BetaPruneTest.class,
    algs.model.tests.gametree.MiniMaxTest.class,
    algs.model.tests.gametree.NegMaxTest.class,
    algs.model.tests.gametree.SimpleTest.class,
    algs.model.tests.heap.HeapTest.class,
    algs.model.tests.intersections.FigureChapter9Test.class,
    algs.model.tests.interval.EnclosingIntervalSearchTest.class,
    algs.model.tests.interval.IntervalCaseTest.class,
    algs.model.tests.interval.SegmentTreeNodeTest.class,
    algs.model.tests.interval.ValidateExtensionsTest.class,
    algs.model.tests.interval.ValidateSegmentTreeTest.class,
    algs.model.tests.kdtree.HypercubeTest.class,
    algs.model.tests.kdtree.HyperpointTest.class,
    algs.model.tests.kdtree.KDExtendedTest.class,
    algs.model.tests.kdtree.KDTest.class,
    algs.model.tests.kdtree.RangeQueryTest.class,
    algs.model.tests.kdtree.TwoDTest.class,
    algs.model.tests.list.DoubleIteratorTest.class,
    algs.model.tests.list.DoubleTest.class,
    algs.model.tests.list.ListTest.class,
    algs.model.tests.network.CormenExampleTest.class,
    algs.model.tests.network.CreateImageTest.class,
    algs.model.tests.network.ExampleTest.class,
    algs.model.tests.network.MaxFlowMinCostTest.class,
    algs.model.tests.network.SampleBackflowTest.class,
    algs.model.tests.network.SimpleTest.class,
    algs.model.tests.network.WebExampleTest.class,
    algs.model.tests.network.matching.Chapter12Test.class,
    algs.model.tests.network.matching.CormenTest.class,
    algs.model.tests.network.matching.DrozdekTest.class,
    algs.model.tests.search.AssociativeHashTableTest.class,
    algs.model.tests.search.BinarySearchTest.class,
    algs.model.tests.search.ListHashTableTest.class,
    algs.model.tests.search.SequentialSearchTest.class,
    algs.model.tests.search.StringFileIteratorTest.class,
    algs.model.tests.searchtree.ClosedStatesTest.class,
    algs.model.tests.searchtree.GenericTests.class,
    algs.model.tests.searchtree.NodeExpansionTest.class,
    algs.model.tests.searchtree.SmallTest.class,
    algs.model.tests.searchtree.ClosedStatesTest.class,
    algs.model.tests.searchtree.GenericTests.class,
    algs.model.tests.searchtree.NodeExpansionTest.class,
    algs.model.tests.searchtree.SmallTest.class,
    algs.model.tests.tictactoe.AlphaBetaTest.class,
    algs.model.tests.tictactoe.CellTest.class,
    algs.model.tests.tictactoe.EightPuzzleNodeTest.class,
    algs.model.tests.tictactoe.EndGameTest.class,
    algs.model.tests.tictactoe.PruneTest.class,
    algs.model.tests.tictactoe.ShowAlphaPruneTest.class,
    algs.model.tests.tictactoe.ShowBetaPruneTest.class,
    algs.model.tests.tictactoe.SlideMoveTest.class,
    algs.model.tests.tree.BinaryTreeTest.class,
    algs.model.tests.tree.RightThreadedTreeTest.class,
    algs.model.tests.twod.IntersectionsTest.class,
    algs.model.tests.twod.RectangleTest.class,
    algs.model.tests.twod.TwoDPointTest.class
})
public class CompleteWithoutPerformanceTestSuite {
    
}
